"""add password reset

Revision ID: 176636187c95
Revises: a10a1875ac23
Create Date: 2026-08-16 12:20:30.061720
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '176636187c95'
down_revision: Union[str, Sequence[str], None] = 'a10a1875ac23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
