"""move otp verification to email_verifications

Revision ID: 3cc181115f98
Revises: 4fe5c8f69c03
Create Date: 2026-08-16 12:04:48.352393
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3cc181115f98'
down_revision: Union[str, Sequence[str], None] = '4fe5c8f69c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
