"""add email verification

Revision ID: 4fe5c8f69c03
Revises: 0001_initial
Create Date: 2026-08-16 09:32:02.343866
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4fe5c8f69c03'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text("false"),))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
